name: "RFCs Action"
description: "GitHub Action to manage your RFCs repository"
author: "Koj <https://github.com/koj.co>"
inputs:
  dirName:
    required: false
    description: "Directory containing RFC documents"
  command:
    required: false
    description: "Command to execute"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
