name: "RFCs Action"
description: "GitHub Action to manage your RFCs repository"
author: "Koj <https://github.com/koj.co>"
inputs:
  token:
    required: true
    description: "GitHub token"
  dirName:
    required: false
    description: "Directory containing RFC documents"
  command:
    required: false
    description: "Command to execute"
  commitEmail:
    required: false
    description: "Email for commit message"
  commitUsername:
    required: false
    description: "Username for commit message"
  teamName:
    required: false
    description: "Team to ping in issue"
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "umbrella"
  color: "purple"
